apiVersion: v1
kind: Secret
metadata:
  name: usersapi-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=FCG_Users;User Id=admin;Password=Admin123456!;TrustServerCertificate=True;"
  Jwt__SecretKey: "k8j2h9d7f6g5h4j3k2l1m0n9b8v7c6x5z4a3s2d1f0"
  DefaultAdmin__Password: "SenhaAdmin123!"
