name: Deploy Microservice to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./FCG.Users
          file: ./FCG.Users/FCG.Users.API/Dockerfile
          target: runtime
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-api-image:latest

      - name: Build and push Migrations image
        uses: docker/build-push-action@v5
        with:
          context: ./FCG.Users
          file: ./FCG.Users/FCG.Users.API/Dockerfile
          target: migrations
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-api-image:migrations

      - name: Copy docker-compose and .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/app"

      - name: Create .env on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/app
            cat > /home/ubuntu/app/.env << 'EOF'
            ${{ secrets.ENV_FILE }}
            EOF

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            cd /home/ubuntu/app
            docker compose pull usersapi-migration usersapi
            docker compose up usersapi-migration --no-deps
            docker compose up -d usersapi --no-deps
            docker compose ps
            docker image prune -f
