name: Deploy Microservice to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build e Push da Imagem
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./FCG.Users/FCG.Users.API
        file: ./FCG.Users/FCG.Users.API/Dockerfile
        push: true
        # AQUI: O nome da imagem no Docker Hub
        # Ex: anaarquiteta/pagamentos-api:latest
        tags: ${{ secrets.DOCKER_USERNAME }}/user-api-image:latest

    # 4. Conecta via SSH e atualiza APENAS este serviço
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 1. Baixa as imagens atualizadas
          docker compose pull usersapi
          docker pull ${{ secrets.DOCKER_USERNAME }}/user-api-image:migrations
          
          # 2. RODA A MIGRATION ANTES DO DEPLOY (Totalmente automatizado)
          docker run --rm --env-file .env ${{ secrets.DOCKER_USERNAME }}/user-api-image:migrations
          
          # 3. Sobe a API nova apenas se a migration acima deu sucesso
          docker compose up -d --no-deps usersapi
          
          # 4. Limpa imagens antigas
          docker image prune -f
